### ISSUE TITLE
4.1.1 not working on macos monterey with m1-chip 

### ISSUE THREAD

**Issue by bendschs** [xilopaint/alfred-pdf-tools#24]
all actions fail with following or similar error message, seems to be a problem with the architecture as the last line is pointing out.

```
[10:48:34.181] Alfred PDF Tools[Arg and Vars] Processing complete
[10:48:34.182] Alfred PDF Tools[Arg and Vars] Passing output '' to Keyword
[10:48:38.139] Alfred PDF Tools[Keyword] Processing complete
[10:48:38.145] Alfred PDF Tools[Keyword] Passing output 'sss' to Run Script
[10:48:38.221] ERROR: Alfred PDF Tools[Run Script] Traceback (most recent call last):
  File "/Users/Benno/Nextcloud/00 Admin/00 Config/B2ARCH/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BF1658D7-B062-4D25-AD6B-17F57B2F1175/alfred_pdf_tools.py", line 48, in <module>
    from PyPDF2 import PdfReader, PdfWriter, PdfMerger, PageRange, PageObject, errors
  File "/Users/Benno/Nextcloud/00 Admin/00 Config/B2ARCH/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BF1658D7-B062-4D25-AD6B-17F57B2F1175/PyPDF2/__init__.py", line 10, in <module>
    from ._encryption import PasswordType
  File "/Users/Benno/Nextcloud/00 Admin/00 Config/B2ARCH/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BF1658D7-B062-4D25-AD6B-17F57B2F1175/PyPDF2/_encryption.py", line 60, in <module>
    from Crypto.Cipher import AES, ARC4  # type: ignore[import]
  File "/Users/Benno/Nextcloud/00 Admin/00 Config/B2ARCH/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BF1658D7-B062-4D25-AD6B-17F57B2F1175/Crypto/Cipher/__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "/Users/Benno/Nextcloud/00 Admin/00 Config/B2ARCH/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BF1658D7-B062-4D25-AD6B-17F57B2F1175/Crypto/Cipher/_mode_ecb.py", line 35, in <module>
    raw_ecb_lib = load_pycryptodome_raw_lib("Crypto.Cipher._raw_ecb", """
  File "/Users/Benno/Nextcloud/00 Admin/00 Config/B2ARCH/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BF1658D7-B062-4D25-AD6B-17F57B2F1175/Crypto/Util/_raw_api.py", line 309, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Not found '_raw_ecb.cpython-39-darwin.so', Cannot load '_raw_ecb.abi3.so': dlopen(/Users/Benno/Nextcloud/00 Admin/00 Config/B2ARCH/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BF1658D7-B062-4D25-AD6B-17F57B2F1175/Crypto/Util/../Cipher/_raw_ecb.abi3.so, 0x0006): tried: '/Users/Benno/Nextcloud/00 Admin/00 Config/B2ARCH/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BF1658D7-B062-4D25-AD6B-17F57B2F1175/Crypto/Util/../Cipher/_raw_ecb.abi3.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))), '/Users/Benno/Nextcloud/00 Admin/00 Config/B2ARCH/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BF1658D7-B062-4D25-AD6B-17F57B2F1175/Crypto/Cipher/_raw_ecb.abi3.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))), Not found '_raw_ecb.so
```

**Comment by xilopaint** [comment]
Please, edit your post using the template.

**Comment by bendschs** [comment]
i am very sorry, but i have no time to do that, i think in between title and post all the info needed is there. if you want to delete it go ahead, i am sure somebody else will bring this up sometime soon.
