### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by felipesafar** [xilopaint/alfred-pdf-tools#4]
Hey.

As soon as I installed Alfred 3 I have downloaded your workflow. I think it might help me a lot on daily tasks. However I can't get it to work and I have already tried a million different ways.

I have installed it without changing any settings. Once I choose a PDF document on Finder I Double Tap Ctrl (hotkey for file selection) and choose SPLIT option from your workflow and then enter the max # of pages. Nothing happens.

What am I doing wrong? Screenshots in attach.

![2017-06-28_09-23-17](https://user-images.githubusercontent.com/27915434/27636880-041f5496-5be4-11e7-945e-a478e1f17d79.jpg)
![2017-06-28_09-26-51](https://user-images.githubusercontent.com/27915434/27636882-0468dd0a-5be4-11e7-9fe9-4a6076ed1075.jpg)

**Comment by xilopaint** [comment]
Click in the debug tool indicated in the screenshot and paste here what you get in the debug console after trying to use the `Split` file action:

![screen shot 2017-06-28 at 11 22 04 am](https://user-images.githubusercontent.com/11052366/27642140-467ae304-5bf4-11e7-8dd1-4fd1cc2df3b4.png)

**Comment by felipesafar** [comment]
Thank you for your quick reply.

Starting debug for 'Alfred PDF Tools'

[2017-06-28 11:47:04][ERROR: action.script] Traceback (most recent call last):
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.124C0CB9-C413-4EFC-954F-7E46AFBD5B16/split_page_count.py", line 76, in <module>
    sys.exit(main())
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.124C0CB9-C413-4EFC-954F-7E46AFBD5B16/split_page_count.py", line 46, in main
    merger.write(no_ext_path + (' (part {}).pdf').format(i + 1))
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.124C0CB9-C413-4EFC-954F-7E46AFBD5B16/PyPDF2/merger.py", line 230, in write
    self.output.write(fileobj)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.124C0CB9-C413-4EFC-954F-7E46AFBD5B16/PyPDF2/pdf.py", line 482, in write
    self._sweepIndirectReferences(externalReferenceMap, self._root)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.124C0CB9-C413-4EFC-954F-7E46AFBD5B16/PyPDF2/pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.124C0CB9-C413-4EFC-954F-7E46AFBD5B16/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.124C0CB9-C413-4EFC-954F-7E46AFBD5B16/PyPDF2/pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.124C0CB9-C413-4EFC-954F-7E46AFBD5B16/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.124C0CB9-C413-4EFC-954F-7E46AFBD5B16/PyPDF2/pdf.py", line 556, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.124C0CB9-C413-4EFC-954F-7E46AFBD5B16/PyPDF2/pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.124C0CB9-C413-4EFC-954F-7E46AFBD5B16/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.124C0CB9-C413-4EFC-954F-7E46AFBD5B16/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.124C0CB9-C413-4EFC-954F-7E46AFBD5B16/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.124C0CB9-C413-4EFC-954F-7E46AFBD5B16/PyPDF2/pdf.py", line 577, in _sweepIndirectReferences
    newobj = data.pdf.getObject(data)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.124C0CB9-C413-4EFC-954F-7E46AFBD5B16/PyPDF2/pdf.py", line 1611, in getObject
    retval = readObject(self.stream, self)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.124C0CB9-C413-4EFC-954F-7E46AFBD5B16/PyPDF2/generic.py", line 66, in readObject
    return DictionaryObject.readFromStream(stream, pdf)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.124C0CB9-C413-4EFC-954F-7E46AFBD5B16/PyPDF2/generic.py", line 585, in readFromStream
    % (utils.hexStr(stream.tell()), key))
PyPDF2.utils.PdfReadError: Multiple definitions in dictionary at byte 0x3270 for key /Type

Felipe Safar
Cel.: (31) 99422-0000

Em 28 de jun de 2017, à(s) 11:26, xilopaint <notifications@github.com<mailto:notifications@github.com>> escreveu:


Click in the debug tool indicated in the screenshot and paste here what you get in the debug console after trying to use the Split file action:

[screen shot 2017-06-28 at 11 22 04 am]<https://user-images.githubusercontent.com/11052366/27642140-467ae304-5bf4-11e7-8dd1-4fd1cc2df3b4.png>

**Comment by xilopaint** [comment]
Please, try this build and tell me if it works.

[Alfred PDF Tools.zip](https://github.com/xilopaint/alfred-pdf-tools/files/1109193/Alfred.PDF.Tools.zip)

**Comment by felipesafar** [comment]
It did not unfortunately. Are you brasilian?

Starting debug for 'Alfred PDF Tools'

[2017-06-28 12:29:30][ERROR: action.script] Traceback (most recent call last):
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.124C0CB9-C413-4EFC-954F-7E46AFBD5B16/split_page_count.py", line 76, in <module>
    sys.exit(main())
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.124C0CB9-C413-4EFC-954F-7E46AFBD5B16/split_page_count.py", line 37, in main
    num_pages = int(reader.getNumPages())
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.124C0CB9-C413-4EFC-954F-7E46AFBD5B16/PyPDF2/pdf.py", line 1150, in getNumPages
    raise utils.PdfReadError("File has not been decrypted")
PyPDF2.utils.PdfReadError: File has not been decrypted

Felipe Safar
Cel.: (31) 99422-0000

Em 28 de jun de 2017, à(s) 12:13, xilopaint <notifications@github.com<mailto:notifications@github.com>> escreveu:


Please, try this build and tell me if it works.

Alfred PDF Tools.zip<https://github.com/xilopaint/alfred-pdf-tools/files/1109193/Alfred.PDF.Tools.zip>

**Comment by xilopaint** [comment]
Is your file encrypted? It seems an issue with your file. Have you tried to use the `Split` file action with other files?

**Comment by felipesafar** [comment]
Starting debug for 'Alfred PDF Tools'

[2017-06-28 12:49:01][ERROR: action.script] Traceback (most recent call last):
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/split_page_count.py", line 76, in <module>
    sys.exit(main())
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/split_page_count.py", line 46, in main
    merger.write(no_ext_path + (' (part {}).pdf').format(i + 1))
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/merger.py", line 230, in write
    self.output.write(fileobj)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 482, in write
    self._sweepIndirectReferences(externalReferenceMap, self._root)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 556, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 577, in _sweepIndirectReferences
    newobj = data.pdf.getObject(data)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 1611, in getObject
    retval = readObject(self.stream, self)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/generic.py", line 66, in readObject
    return DictionaryObject.readFromStream(stream, pdf)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/generic.py", line 585, in readFromStream
    % (utils.hexStr(stream.tell()), key))
PyPDF2.utils.PdfReadError: Multiple definitions in dictionary at byte 0x3270 for key /Type

I have just tried splitting the file in attach in 2 parts (1 page each). There was an error on the output file. Size: 0 kb.


[cid:536cd3e5-e70f-4af1-87c7-85ccaa395262@namprd12.prod.outlook.com]

Felipe Safar
Cel.: (31) 99422-0000

Em 28 de jun de 2017, à(s) 12:13, xilopaint <notifications@github.com<mailto:notifications@github.com>> escreveu:


Please, try this build and tell me if it works.

Alfred PDF Tools.zip<https://github.com/xilopaint/alfred-pdf-tools/files/1109193/Alfred.PDF.Tools.zip>

**Comment by felipesafar** [comment]
Starting debug for 'Alfred PDF Tools'

[2017-06-28 12:49:01][ERROR: action.script] Traceback (most recent call last):
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/split_page_count.py", line 76, in <module>
    sys.exit(main())
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/split_page_count.py", line 46, in main
    merger.write(no_ext_path + (' (part {}).pdf').format(i + 1))
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/merger.py", line 230, in write
    self.output.write(fileobj)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 482, in write
    self._sweepIndirectReferences(externalReferenceMap, self._root)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 556, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 577, in _sweepIndirectReferences
    newobj = data.pdf.getObject(data)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/pdf.py", line 1611, in getObject
    retval = readObject(self.stream, self)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/generic.py", line 66, in readObject
    return DictionaryObject.readFromStream(stream, pdf)
  File "/Users/felipesafar/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C896FD40-DD79-45F8-9FB2-55F11648A325/PyPDF2/generic.py", line 585, in readFromStream
    % (utils.hexStr(stream.tell()), key))
PyPDF2.utils.PdfReadError: Multiple definitions in dictionary at byte 0x3270 for key /Type

I have just tried splitting the file in attach in 2 parts (1 page each). There was an error on the output file. Size: 0 kb.


[cid:04cd3727-fccb-4661-8ab6-b1362626776e@namprd12.prod.outlook.com]


Felipe Safar
Cel.: (31) 99422-0000

Em 28 de jun de 2017, à(s) 12:37, xilopaint <notifications@github.com<mailto:notifications@github.com>> escreveu:


Is your file encrypted? It seems an issue with your file. Have you tried to use the Split file action with other files?

**Comment by xilopaint** [comment]
Could you share the file? I will try to sort it out.

**Comment by felipesafar** [comment]
Sure.


Felipe Safar
Cel.: (31) 99422-0000

Em 28 de jun de 2017, à(s) 13:31, xilopaint <notifications@github.com<mailto:notifications@github.com>> escreveu:


Could you share the file? I will try to sort it out.

**Comment by xilopaint** [comment]
Well, you can share the file in this thread by dragging and dropping it on the comment field.

**Comment by felipesafar** [comment]
File in attach as requested. Some files the wkfl works and some file it does not.

[Azul Linhas Aéreas Brasileiras.pdf](https://github.com/xilopaint/alfred-pdf-tools/files/1109803/Azul.Linhas.Aereas.Brasileiras.pdf)

**Comment by xilopaint** [comment]
It worked for me with the build I shared with you. Are you sure you downloaded and installed it properly?

**Comment by felipesafar** [comment]
Yes. 100% sure.

I even removed the last build before installing the new build.

I just tries it aigan and it keeps creating a 0 kb file.

Felipe Safar
Cel.: (31) 99422-0000

Em 28 de jun de 2017, à(s) 15:57, xilopaint <notifications@github.com<mailto:notifications@github.com>> escreveu:


It worked for me with the build I shared with you. Are you sure you downloaded and installed it properly?

**Comment by xilopaint** [comment]
I am sorry, that was my fault. I updated that comment with the correct build. Could you please download it again and tell me if it works for you?

**Comment by felipesafar** [comment]
It worked! Ty!

**Comment by xilopaint** [comment]
Nice. The next stable release will contain the fix. Thanks for spotting the bug.

**Comment by felipesafar** [comment]
Hi.

Can you please send me some kind of manual to explain how does it work?

I have been trying to use it however with no success. I have just started to use Alfred.

Thank you!

Felipe Safar
Cel.: (31) 99422-0000

**Comment by felipesafar** [comment]
I have seen a lot of functions and I need to know how to trigger them.

Felipe Safar
Cel.: (31) 99422-0000

Em 17 de ago de 2018, à(s) 15:45, Felipe Safar <felipe.safar@hotmail.com<mailto:felipe.safar@hotmail.com>> escreveu:

Hi.

Can you please send me some kind of manual to explain how does it work?

I have been trying to use it however with no success. I have just started to use Alfred.

Thank you!

Felipe Safar
Cel.: (31) 99422-0000

**Comment by xilopaint** [comment]
How can you have just started to use Alfred? This issue was created by you one year ago. Btw, there's no manual. If you have a particular question you can ask.

**Comment by felipesafar** [comment]
Ok. Wait.

Last time there was people I worked with who were using my Mac for some tasks.

Now I’m trying to figure out how does Alfred works in order to use the workflows they download and to create my own.

Not easy…

Felipe Safar
Cel.: (31) 99422-0000

Em 17 de ago de 2018, à(s) 16:04, Arthur Pinheiro <notifications@github.com<mailto:notifications@github.com>> escreveu:


How can you have just started to use Alfred? This issue was created by you one year ago. Btw, there's no manual. If you have a particular question you can ask.

**Comment by xilopaint** [comment]
No problem. As I said, feel free to ask what you want to know about this workflow. Also, if you are interested in Alfred in general the [Alfred Forum](https://www.alfredforum.com) should be your best bet.

**Comment by felipesafar** [comment]
Quick question:

There are so many thing I can do with Alfred PDF Tools. Can you explain me how to trigger ANY of them? The rest I guarantee I will figure out myself.

I did not make any changes to the last version.

Felipe Safar
Cel.: (31) 99422-0000

Em 17 de ago de 2018, à(s) 16:28, Arthur Pinheiro <notifications@github.com<mailto:notifications@github.com>> escreveu:


No problem. As I said, feel free to ask what you want to know about this workflow. Also, if you are interested in Alfred in general the Alfred Forum<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.alfredforum.com&data=02%7C01%7C%7Cf82f638df35f4d3b5bd108d604779d54%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636701309113887070&sdata=JFrBASDsdhuvwMezPxGFBBV5guDoD57ECXROKE3KrFU%3D&reserved=0> should be your best bet.

**Comment by xilopaint** [comment]
Alfred PDF Tools is fully operated by file actions. Read [this link](https://www.alfredapp.com/blog/tips-and-tricks/file-actions-from-alfred-or-finder/) to learn how to trigger a file action. Also, you can see #2 and #6 issues to have an idea.

**Comment by felipesafar** [comment]
Thank you!

Felipe Safar
Cel.: (31) 99422-0000

Em 17 de ago de 2018, à(s) 17:00, Arthur Pinheiro <notifications@github.com<mailto:notifications@github.com>> escreveu:


Alfred PDF Tools is fully operated by file actions. Read this link<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.alfredapp.com%2Fblog%2Ftips-and-tricks%2Ffile-actions-from-alfred-or-finder%2F&data=02%7C01%7C%7C5de9f4d6027a4f3e026d08d6047c1275%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636701328258546864&sdata=JnVUMwytO3cyMVJauFMEcQoKgp%2BGjSfkIx7M1BRUeH0%3D&reserved=0> to learn how to trigger a file action. Also, you can see #2<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fxilopaint%2Falfred-pdf-tools%2Fissues%2F2&data=02%7C01%7C%7C5de9f4d6027a4f3e026d08d6047c1275%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636701328258546864&sdata=wy%2F3s%2BGQm25OCr1n1hGToKJz1NJuWauHvkmNCy5f7rM%3D&reserved=0> and #6<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fxilopaint%2Falfred-pdf-tools%2Fissues%2F6&data=02%7C01%7C%7C5de9f4d6027a4f3e026d08d6047c1275%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636701328258546864&sdata=Re4a9sENNs0RYorSmy%2BpcTUm9mJcqxvJALtT6UOqcfU%3D&reserved=0> issues to have an idea.

**Comment by manil88j86** [comment]
Hello! I am having issues getting this to work on Alfred 4. For example, here is the error log when I try to merge two PDFs:

![image](https://user-images.githubusercontent.com/106078457/169810310-729ad00a-52ea-4417-ae41-8d0732dffbb8.png)

[12:27:29.489] Logging Started...
[12:27:37.628] Alfred PDF Tools[[File Action](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8C6DC778-2C74-45CB-8B0A-FF78643F7E63%3EA6A91646-8622-45F4-B763-4A6ACBAFD08C)] Processing complete
[12:27:37.632] Alfred PDF Tools[[File Action](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8C6DC778-2C74-45CB-8B0A-FF78643F7E63%3EA6A91646-8622-45F4-B763-4A6ACBAFD08C)] Passing output '(
    "/Users/joannamain/Library/Mobile Documents/com~apple~CloudDocs/ForjoFurniture/Brochure/brochure.pdf",
    "/Users/joannamain/Library/Mobile Documents/com~apple~CloudDocs/ForjoFurniture/Brochure/CT-580-580-O Drawing .pdf"
)' to [Arg and Vars](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8C6DC778-2C74-45CB-8B0A-FF78643F7E63%3E2412A11E-00A7-400B-90FD-BAEBC00EA23A)
[12:27:37.633] Alfred PDF Tools[[Arg and Vars](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8C6DC778-2C74-45CB-8B0A-FF78643F7E63%3E2412A11E-00A7-400B-90FD-BAEBC00EA23A)] Processing complete
[12:27:37.634] Alfred PDF Tools[[Arg and Vars](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8C6DC778-2C74-45CB-8B0A-FF78643F7E63%3E2412A11E-00A7-400B-90FD-BAEBC00EA23A)] Passing output '' to [Keyword](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8C6DC778-2C74-45CB-8B0A-FF78643F7E63%3ECEBD82BA-6268-426D-9BFE-62BCD4C27471)
[12:27:42.351] Alfred PDF Tools[[Keyword](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8C6DC778-2C74-45CB-8B0A-FF78643F7E63%3ECEBD82BA-6268-426D-9BFE-62BCD4C27471)] Processing complete
[12:27:42.354] Alfred PDF Tools[[Keyword](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8C6DC778-2C74-45CB-8B0A-FF78643F7E63%3ECEBD82BA-6268-426D-9BFE-62BCD4C27471)] Passing output 'test' to [Run Script](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8C6DC778-2C74-45CB-8B0A-FF78643F7E63%3ECF8EFD70-FC46-46DA-85B7-5C40E39C3722)
[12:27:43.551] ERROR: Alfred PDF Tools[[Run Script](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.8C6DC778-2C74-45CB-8B0A-FF78643F7E63%3ECF8EFD70-FC46-46DA-85B7-5C40E39C3722)] [3254] Error loading Python lib '/var/folders/rs/9pnx32rj6ql4pmg8sxbdt0100000gn/T/_MEIFk4zJt/Python': dlopen: dlopen(/var/folders/rs/9pnx32rj6ql4pmg8sxbdt0100000gn/T/_MEIFk4zJt/Python, 10): Symbol not found: _preadv
  Referenced from: /var/folders/rs/9pnx32rj6ql4pmg8sxbdt0100000gn/T/_MEIFk4zJt/Python (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by xilopaint** [comment]
@manil88j86 your issue is not related to this one. Please, open a new issue using the template.

**Comment by manil88j86** [comment]
Thank you. I have re-posted it here:
[https://github.com/xilopaint/alfred-pdf-tools/issues/18#issue-1246341661]
